#!/bin/bash

# Link to the binary
ln -sf '/opt/Termius/termius-app' '/usr/bin/termius-app'

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/Termius/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
